name: test

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - run: sudo apt-get update && sudo apt-get install -y libpcap-dev
      - run: go test ./...
      - run: go vet ./...
